<a href="https://colab.research.google.com/github/jiminmini/mini/blob/ESAA_OB_%EC%84%B8%EC%85%98(%EA%B8%88)/11_14_%EC%84%B8%EC%85%98_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
import torch

# Create random tensor
tensor = torch.rand(7, 7)
print(tensor)

tensor([[0.6326, 0.1986, 0.4980, 0.4745, 0.9149, 0.3343, 0.2452],
        [0.5812, 0.6802, 0.8385, 0.4119, 0.4976, 0.7680, 0.1632],
        [0.9305, 0.4461, 0.2500, 0.7051, 0.9668, 0.0991, 0.4033],
        [0.5309, 0.3141, 0.2071, 0.1886, 0.9218, 0.4230, 0.8017],
        [0.7530, 0.7284, 0.3413, 0.0196, 0.2231, 0.4584, 0.5549],
        [0.4874, 0.7508, 0.0098, 0.4061, 0.4940, 0.9693, 0.4842],
        [0.8824, 0.1342, 0.8938, 0.4189, 0.8384, 0.4461, 0.3152]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor with shape (1, 7)
tensor2 = torch.rand(1, 7)

# Perform matrix multiplication (transpose tensor2 to (7, 1))
result = torch.matmul(tensor, tensor2.T)

print(result.shape)  # -> torch.Size([7, 1])
print(result)

torch.Size([7, 1])
tensor([[1.4975],
        [1.9305],
        [1.8757],
        [1.6999],
        [1.7102],
        [1.9984],
        [1.8030]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)

# Matrix multiply tensors
result = torch.matmul(tensor, tensor2.T)

print(result, result.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
import torch

# Set random seed on the GPU
torch.cuda.manual_seed(1234)        # 단일 GPU
torch.cuda.manual_seed_all(1234)    # 멀티 GPU 환경


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [5]:
import torch

# Set random seed for reproducibility (CPU)
torch.manual_seed(1234)

# Check for access to GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# Create two random tensors of shape (2, 3) and move them to GPU
tensor1 = torch.rand(2, 3, device=device)
tensor2 = torch.rand(2, 3, device=device)

print(tensor1, tensor2)

Device: cuda
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [6]:
import torch

# Set random seed for reproducibility
torch.manual_seed(1234)

# Check for access to GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Create two random tensors on GPU
tensor_A = torch.rand(2, 3, device=device)
tensor_B = torch.rand(2, 3, device=device)

# Perform matrix multiplication (adjust shape of tensor_B by transposing)
result = torch.matmul(tensor_A, tensor_B.T)

print(result, result.shape)

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [7]:
# Find max
max_value = result.max()
print("Max:", max_value)

# Find min
min_value = result.min()
print("Min:", min_value)

Max: tensor(0.7668, device='cuda:0')
Min: tensor(0.2786, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [8]:
# Find arg max
max_index = result.argmax()
print("Arg max:", max_index)

# Find arg min
min_index = result.argmin()
print("Arg min:", min_index)

Arg max: tensor(1, device='cuda:0')
Arg min: tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [9]:
import torch

# Set seed
torch.manual_seed(7)

# Create random tensor with shape (1, 1, 1, 10)
tensor1 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor2 = tensor1.squeeze()

# Print out tensors and their shapes
print(tensor1, tensor1.shape)
print(tensor2, tensor2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
