<a href="https://colab.research.google.com/github/jiminmini/mini/blob/ESAA_OB/11_3_%ED%95%84%EC%82%AC_%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**[개념 정리]**

**[인공지능, 머신러닝과 딥러닝]**
- 인공지능> 머신 러닝> 딥러닝

**[머신러닝]**
- 학습 단계
- 예측 단계
--> 분류 및 예측 결과 도출

**[머신러닝 학습 알고리즘]**
- 지도 학습: 정답 알려준 후 학습
- 비지도 학습: 정답 알려주지 않고 예측
- 강화 학습: 행동에 대한 보산을 받으며 학습

**[딥러닝]**
- 데이터 준비> 모델 정의> 모델 컴파일> 모델 훈련> 모델 예측

**[파이토치]**
- 파이토치 API: 사용자 인터페이스 제공
- 파이토치 엔진



#**[코드 필사]**

In [1]:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Looking in indexes: https://download.pytorch.org/whl/cu118


In [2]:
import torch
print(torch . tensor( [[ 1, 2] , [3 ,4]]))
print(torch .tensor([[1 , 2] , [3 ,4]] , device="cuda:0" ))
print (torch . tensor( [ [1 , 2] , [3, 4] ], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [3]:
temp = torch.tensor([[1 , 2] , [3,4]])
print (temp.numpy())
temp = torch .tensor([[1 , 2], [3 , 4] ], device="cuda:0" )
print( temp.to( "cpu" ).numpy())

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [4]:
temp = torch .FloatTensor([1 , 2, 3, 4, 5, 6, 7])
print( temp [0], temp [1], temp [-1])
print( '------------------------' )
print (temp [2:5 ], temp[4: -1])

tensor(1.) tensor(2.) tensor(7.)
------------------------
tensor([3., 4., 5.]) tensor([5., 6.])


In [5]:
v = torch. tensor( [1 , 2, 3])
w = torch.tensor([ 3, 4, 6])
print (w - v )

tensor([2, 2, 3])


In [6]:
temp = torch.tensor([ [1 , 2], [3, 4]])
print(temp.shape)
print ( '------------------------' )
print( temp.view( 4, 1))
print ( '------------------------' )
print( temp.view( -1))
print( '-------------------------' )
print( temp.view( 1, - 1) )
print( '------------------------' )
print (temp.view ( - 1, 1) )

torch.Size([2, 2])
------------------------
tensor([[1],
        [2],
        [3],
        [4]])
------------------------
tensor([1, 2, 3, 4])
-------------------------
tensor([[1, 2, 3, 4]])
------------------------
tensor([[1],
        [2],
        [3],
        [4]])


In [7]:
pip install pandas

In [ ]:
import pandas as pd
import torch
data=pd.read_csv(' .. /class2.csv ')

x= torch.from_numpy( data ['x' ]. values) .unsqueeze( dim=1).float()
y = torch .from_numpy( data [ 'y'] . values) . unsqueeze (dim=1 ).float()

In [ ]:
class CustomDataset(torch.utils.data .Dataset):
    def __init__(self):
    def __len__(self):
    def __getitem__(self, index):

In [ ]:
import pandas as pd
import torch
from torch.utils .data import Dataset
from torch.utils.data import DataLoader

class CustomDataset(Dataset):
    def __init__(self, csv_file):
        self.label = pd .read_csv (csv_file)
    def __len__(self):
        return len(self.label)
    def __getitem__(self, idx):
        sample = torch.tensor(self .label.iloc[idx, 0:3]).int()
        label = torch.tensor(self.label.iloc[idx, 3]).int()
        return sample , label
tensor_dataset = CustomDataset( ' .. /covtype.csv ')
dataset = DataLoader(tensor_dataset, batch_size=4, shuffle=True )

In [ ]:
for i, data in enumerate(dataset,0):
    print(i,end='')
    batch=data[0]
    print(batch.size())

In [9]:
pip install requests

In [11]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [12]:
import torchvision.transforms as transforms
mnist_transform = transforms.Compose([
    transforms.ToTensor() ,
    transforms. Normalize( (0.5,), (1.0,))
])

from torchvision.datasets import MNIST
import requests
download_root = '/content/drive/MyDrive/ESAA/data/MNIST_DATASET'
train_dataset = MNIST(download_root, transform=mnist_transform, train=True ,
download=True )
valid_dataset = MNIST(download_root, transform=mnist_transform, train=False,
download=True )
test_dataset = MNIST(download_root, transform=mnist_transform, train=False,
download=True )

In [13]:
import torch
import torch.nn as nn
model=nn.Linear(in_features=1, out_features=1, bias=True)

In [14]:
class MLP(nn.Module):
    def __init__(Self, inputs):
        super(MLP, self).__init__()
        self.layer=Linear(inputs,1)
        self.activation=Sigmoid()

    def forward(self, x):
        x=self.layer(x)
        x=self.activation(x)
        return x

In [15]:
import torch.nn as nn
class MLP (nn .Module ):
    def __init__ (self):
        super(MLP , self). __init__()
        self.layer1 = nn .Sequential(
            nn .Conv2d(in_channels=3, out_channels=64, kernel_size=5) ,
            nn .ReLU(inplace=True ),
            nn .MaxPool2d(2))

        self.layer2 = nn .Sequential(
            nn .Conv2d(in_channels=64, out_channels=30, kernel_size=5) ,
            nn .ReLU(inplace=True ),
            nn .MaxPool2d(2))

        self.layer3 = nn .Sequential(
            nn .Linear(in_features=30*5*5, out_features=10, bias=True ),
            nn .ReLU(inplace=True ))

        def forward (self, x):
            x = self.layer1( x)
            x = self.layer2(x)
            x = x.view(x .shape[0] , -1)
            x = self.layer3(x)
            return x
model = MLP()
print ("Printing children\n------------------------------" )
print(list(model .children()))
print ( "\n\nPrinting Modules\n------------------------------" )
print(list(model .modules()))

Printing children
------------------------------
[Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)]


Printing Modules
------------------------------
[MLP(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer3): Sequential(
    (0): Linea

In [16]:
def MLP (in_features=1, hidden_features=20, out_features=1):
    hidden = nn.Linear( in_features=in_features, out_features=hidden_features,
                            bias=True )
    activation = nn.ReLU()
    output = nn.Linear(in_features=hidden_features, out_features=out_features,
                        bias=True )
    net = nn.Sequential( hidden , activation , output)
    return net

In [17]:
import torch
from torch.utils.data import DataLoader, TensorDataset

# 예시 데이터
x_train = torch.randn(100, 1)
y_train = 2 * x_train + 1

# DataLoader 생성
dataset = TensorDataset(x_train, y_train)
dataloader = DataLoader(dataset, batch_size=10, shuffle=True)

# 모델 정의 (예시)
model = torch.nn.Linear(1, 1)

# 손실함수, 옵티마이저, 스케줄러
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda=lambda epoch: 0.95 ** epoch)

# 학습 루프
for epoch in range(1, 101):
    for x, y in dataloader:
        optimizer.zero_grad()
        loss = criterion(model(x), y)   # 손실 계산
        loss.backward()                 # 역전파
        optimizer.step()                # 파라미터 업데이트
    scheduler.step()                    # LR 스케줄러 업데이트

In [18]:
for epoch in range (100):
    yhat = model(x_train)
    loss = criterion(yhat , y_train)
    optimizer. zero_grad()
    loss.backward()
    optimizer.step()

In [19]:
pip install torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.2/983.2 kB 64.4 MB/s eta 0:00:00


In [20]:
import torch
import torchmetrics

# 예시 데이터
preds = torch.randn(10, 5).softmax(dim=-1)  # 10개 샘플, 클래스 5개
target = torch.randint(0, 5, (10,))         # 0~4 클래스 라벨

# accuracy 계산
acc = torchmetrics.functional.accuracy(
    preds, target, task="multiclass",  num_classes=5
)

print(acc)


tensor(0.2000)


In [21]:
import torch
import torchmetrics

# Accuracy metric 객체 생성
metric = torchmetrics.Accuracy(task="multiclass", num_classes=5)

n_batches = 10
for i in range(n_batches):
    preds = torch.randn(10, 5).softmax(dim=-1)
    target = torch.randint(0, 5, (10,))

    acc = metric(preds, target)
    print(f"Accuracy on batch {i}: {acc}")

# 전체 배치에 대한 accuracy
acc = metric.compute()
print(f"Accuracy on all data: {acc}")

Accuracy on batch 0: 0.0
Accuracy on batch 1: 0.10000000149011612
Accuracy on batch 2: 0.20000000298023224
Accuracy on batch 3: 0.4000000059604645
Accuracy on batch 4: 0.4000000059604645
Accuracy on batch 5: 0.20000000298023224
Accuracy on batch 6: 0.4000000059604645
Accuracy on batch 7: 0.30000001192092896
Accuracy on batch 8: 0.20000000298023224
Accuracy on batch 9: 0.10000000149011612
Accuracy on all data: 0.23000000417232513


In [22]:
 pip install tensorboard

In [ ]:
import torch
from torch.utils.tensorboard import SummaryWriter

num_epochs = 20
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 모델 정의
model = LSTMModel(input_dim=X_train_tensors_f.shape[2])
model = model.to(device)  # 먼저 GPU로 이동

# optimizer와 criterion은 그 다음에 정의해야 함!
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
criterion = torch.nn.MSELoss()

writer = SummaryWriter("/content/drive/MyDrive/ESAA/11.3_필사과제_자료")

for epoch in range(num_epochs):
    model.train()
    for i, (x, y) in enumerate(dataloader):
        x, y = x.to(device).float(), y.to(device).float()
        optimizer.zero_grad()
        outputs = model(x)
        loss = criterion(outputs, y)
        loss.backward()
        optimizer.step()

        writer.add_scalar("Loss", loss.item(), epoch * len(dataloader) + i)

writer.close()

In [24]:
!tensorboard --logdir=../chap02/tensorboard --port=6006

/usr/local/lib/python3.12/dist-packages/tensorboard/_vendor/bleach/sanitizer.py:292: SyntaxWarning: invalid escape sequence '\s'
  "[`\000-\040\177-\240\s]+",
/usr/local/lib/python3.12/dist-packages/tensorboard/_vendor/bleach/sanitizer.py:339: SyntaxWarning: invalid escape sequence '\s'
  style = re.compile('url\s*\(\s*[^\s)]+?\s*\)\s*').sub(' ', style)
/usr/local/lib/python3.12/dist-packages/tensorboard/_vendor/bleach/sanitizer.py:354: SyntaxWarning: invalid escape sequence '\s'
  if not re.match("^\s*([-\w]+\s*:[^:;]*(;\s*|$))*$", style):
/usr/local/lib/python3.12/dist-packages/tensorboard/_vendor/bleach/sanitizer.py:358: SyntaxWarning: invalid escape sequence '\w'
  for prop, value in re.findall('([-\w]+)\s*:\s*([^:;]*)', style):
2025-11-03 01:09:30.338194: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1762132170.357512    3320 cuda_dnn.

In [ ]:
model.eval()
with torch.no_grad( ):
    valid_loss = 0

    for x, y in valid_dataloader:
        outputs = model(x)
        loss = F.cross_entropy(outputs, y.long().squeeze())
        valid_loss += float (loss)
        y_hat += [outputs]

va1id_loss = valid_loss / len(valid_loader)