<a href="https://colab.research.google.com/github/jiminmini/mini/blob/main/9_19_%ED%95%84%EC%82%AC%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**[개념 정리]**

##**[가우시안 혼합]**
- 샘플이 파라미터가 알려지지 않은 여러 개의 혼합된 가우시안 분포에서 생성되었다고 가정하는 확률 모델

##**[가우시안 혼합을 사용한 이상치 탐지]**
- 밀도 임곗값 설정
- 특이치 탐지와 유사


##**[클러스터 개수 선택하기]**
- BIC나 AIC와 같은 이론적 정보 기준을 최소화하는 모델 찾기
- 가능도 함수


##**[베이즈 가우시안 혼합 모델]**
- 베타 분포: 고정 범위 안에 놓인 값을 가진 확률 변수를 모델링할 때 자주 사용

- 블랙박스 확률적 변분 추론: ELBO를 최대화하는 간단한 방법

#**[코드 필사]**

In [ ]:
from sklearn.mixture import GaussianMixture
gm=GaussianMixture(n_components=3, n_init=10)
gm.fit(x)

GaussianMixture(n_components=3, n_init=10)

In [ ]:
gm.weights_

array([0.58444825, 0.2096565 , 0.20589525])

In [ ]:
gm.means_

array([[ 0.49662758,  0.25205688],
       [ 1.72865309, -0.06805328],
       [-0.74180549,  0.56922905]])

In [ ]:
gm.covariances_

array([[[ 0.16482018, -0.09496613],
        [-0.09496613,  0.28419168]],

       [[ 0.06018379,  0.06707337],
        [ 0.06707337,  0.09137884]],

       [[ 0.05588975,  0.06324128],
        [ 0.06324128,  0.08663075]]])

In [ ]:
gm.converged_

True

In [ ]:
gm.n_iter_

16

In [ ]:
gm.predict(x)

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 2, 1, 1, 0, 0, 2, 1, 0, 1, 2, 2, 0,
       1, 0, 0, 0, 0, 1, 2, 1, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 0, 1, 0, 0,
       1, 0, 0, 2, 0, 0, 2, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 2, 1, 0, 0, 1, 1, 2, 2, 0, 0, 2, 0, 0, 1, 2, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 2, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 2, 0, 1, 0, 1, 1,
       2, 2, 1, 2, 0, 2, 2, 1, 2, 0, 1, 1, 1, 2, 2, 0, 0, 0, 2, 1, 1, 0,
       1, 0, 0, 2, 2, 1, 0, 1, 0, 0, 2, 0, 1, 2, 2, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 1, 0, 0, 0, 0, 2,
       2, 0, 1, 0, 2, 0, 1, 0, 2, 2, 1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 2,
       0, 2, 0, 0, 1, 0, 0, 1, 1, 2, 2, 0, 2, 1, 1,

In [ ]:
gm.predict_proba(x)

array([[6.79578641e-001, 7.87413523e-150, 3.20421359e-001],
       [8.35799268e-001, 1.17633331e-144, 1.64200732e-001],
       [2.19504585e-004, 9.99780495e-001, 4.05144401e-184],
       ...,
       [4.66170690e-004, 1.35706932e-158, 9.99533829e-001],
       [1.00000000e+000, 3.31994249e-062, 6.44896827e-031],
       [1.00000000e+000, 1.40101800e-074, 1.26337543e-022]])

In [ ]:
x_new,y_new=gm.sample(6)
x_new

array([[ 1.25002314, -0.11748496],
       [ 0.30382379, -0.15389352],
       [ 1.10934433,  0.55272113],
       [ 1.69253132, -0.10550103],
       [-0.55652609,  0.66583058],
       [-0.799607  ,  0.33060903]])

In [ ]:
y_new

array([0, 0, 0, 1, 2, 2])

In [ ]:
gm.score_samples(x)

array([-2.13674225e+00, -2.26587084e+00, -1.28626175e+00, -1.65780934e+00,
       -2.12682172e+00, -2.19652065e+00, -2.10591778e+00, -1.92275276e+00,
       -1.59209834e+00, -8.90857914e-01, -1.43103384e-01,  9.78388327e-03,
       -1.73929414e+00, -1.66412551e+00, -1.71959858e+00, -5.02298770e-01,
       -5.62178140e-01, -1.58458904e+00, -1.12906336e+00, -1.51008281e-03,
        2.37697862e-03, -1.74764806e+00, -1.67370498e+00, -1.34101408e+00,
       -1.75994978e+00, -1.56808633e+00, -1.75511237e+00, -2.99145234e-01,
       -1.81060971e+00, -1.08435957e+00, -2.80829797e-01, -1.31567110e+00,
       -6.65828603e-01, -1.31067709e-01, -1.75924515e+00, -1.43332282e+00,
       -2.01370492e+00, -1.67834167e+00, -2.95376698e-01, -3.60899835e-01,
       -1.90248914e+00, -4.93132297e-01, -1.90828670e+00, -1.55900416e+00,
       -5.66001574e-01, -1.54527017e+00, -1.44310261e+00, -1.00676540e+00,
       -1.42561704e+00, -1.79418632e+00, -8.13095437e-02, -1.33898075e+00,
       -1.90201109e+00, -

In [ ]:
densities=gm.score_samples(x)
density_threshold=np.percentile(densities,4)
anomalies=x[densities<density_threshold]

In [ ]:
gm.bic(x)

np.float64(2771.115138509054)

In [ ]:
gm.aic(x)

np.float64(2687.6832987663574)

In [ ]:
from sklearn.mixture import BayesianGaussianMixture
bgm=BayesianGaussianMixture(n_components=10,n_init=10)
bgm.fit(x)
np.round(bgm.weights_,2)

/usr/local/lib/python3.12/dist-packages/sklearn/mixture/_base.py:269: ConvergenceWarning: Best performing initialization did not converge. Try different init parameters, or increase max_iter, tol, or check for degenerate data.
  warnings.warn(


array([0.13, 0.1 , 0.15, 0.13, 0.11, 0.14, 0.16, 0.08, 0.  , 0.  ])