<a href="https://colab.research.google.com/github/jiminmini/mini/blob/ESAA_OB/9_19_%ED%95%84%EC%82%AC%EA%B3%BC%EC%A0%9C%20%EC%B5%9C%EC%A2%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**[개념 정리]**

##**[가우시안 혼합]**
- 샘플이 파라미터가 알려지지 않은 여러 개의 혼합된 가우시안 분포에서 생성되었다고 가정하는 확률 모델

##**[가우시안 혼합을 사용한 이상치 탐지]**
- 밀도 임곗값 설정
- 특이치 탐지와 유사


##**[클러스터 개수 선택하기]**
- BIC나 AIC와 같은 이론적 정보 기준을 최소화하는 모델 찾기
- 가능도 함수


##**[베이즈 가우시안 혼합 모델]**
- 베타 분포: 고정 범위 안에 놓인 값을 가진 확률 변수를 모델링할 때 자주 사용

- 블랙박스 확률적 변분 추론: ELBO를 최대화하는 간단한 방법

#**[코드 필사]**

In [4]:
import numpy as np
from sklearn.datasets import make_moons

x, y = make_moons(n_samples=1000,noise=0.05)

In [2]:
# 데이터 불러오기
from sklearn.datasets import make_blobs
import numpy as np

# make_blobs()의 정확한 인수는 중요하지 않습니다.

blob_centers = np.array([[ 0.2, 2.3], [-1.5 , 2.3], [-2.8, 1.8], [-2.8, 2.8], [-2.8, 1.3]])

blob_std = np.array([0.4, 0.3, 0.1, 0.1, 0.1])

x, y = make_blobs(n_samples=2000, centers=blob_centers, cluster_std=blob_std, random_state=7)

In [3]:
from sklearn.mixture import GaussianMixture
gm=GaussianMixture(n_components=3, n_init=10)
gm.fit(x)

GaussianMixture(n_components=3, n_init=10)

In [5]:
gm.weights_

array([0.20032189, 0.59989596, 0.19978216])

In [6]:
gm.means_

array([[ 0.19937187,  2.25813691],
       [-2.80278963,  1.96665812],
       [-1.48543693,  2.28573643]])

In [7]:
gm.covariances_

array([[[ 1.46166449e-01, -4.84946828e-03],
        [-4.84946828e-03,  1.56280672e-01]],

       [[ 9.95376970e-03,  7.16529541e-04],
        [ 7.16529541e-04,  3.96947649e-01]],

       [[ 8.79984367e-02,  1.46541758e-04],
        [ 1.46541758e-04,  9.01630979e-02]]])

In [8]:
gm.converged_

True

In [9]:
gm.n_iter_

3

In [10]:
gm.predict(x)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [11]:
gm.predict_proba(x)

array([[1.00000000e+000, 0.00000000e+000, 1.15452282e-029],
       [1.00000000e+000, 1.28813624e-290, 4.15257639e-017],
       [1.00000000e+000, 6.28364346e-194, 7.11063993e-014],
       ...,
       [9.99999998e-001, 1.34272529e-197, 1.76167855e-009],
       [1.00000000e+000, 1.57847413e-316, 1.80229380e-023],
       [1.00000000e+000, 3.08952094e-318, 1.23023894e-020]])

In [12]:
x_new,y_new=gm.sample(6)
x_new

array([[-2.72751083,  2.27172297],
       [-2.85239982,  2.26116009],
       [-1.37722399,  2.3314358 ],
       [-1.46667594,  2.01432294],
       [-1.60320486,  3.03613467],
       [-1.57070634,  2.33054995]])

In [13]:
y_new

array([1, 1, 2, 2, 2, 2])

In [14]:
gm.score_samples(x)

array([-26.57551225, -12.97373126, -19.98082824, -18.66477157,
       -25.78155725, -17.59251835, -26.05043983, -13.26937797,
       -22.27315189, -11.61788334, -12.77631347, -21.36330087,
       -11.40499942, -19.36272135, -27.30315261, -20.18928768,
       -28.67443959, -23.81336415, -14.41566128, -13.64036207,
       -28.04823794,  -9.13658559, -27.18336949, -25.89295865,
       -18.11249203, -21.96394207, -19.60673202, -12.3870912 ,
       -16.39996074, -28.35242184, -18.70163653, -23.29288355,
       -29.75270591, -27.94379453, -20.68645197, -19.83840907,
        -7.31025447,  -6.60153135, -14.32897325, -17.2895076 ,
       -18.46299869, -13.91835555, -18.34368392, -13.54991532,
       -27.57367631, -12.53959823,  -7.01564286, -21.43162543,
       -16.60764103,  -7.04473696,  -8.79006893, -18.89450343,
       -23.43762576, -18.22001285, -26.32931131, -14.52374242,
       -22.98775949, -24.45524122,  -8.50366805,  -6.57947883,
       -23.03141853, -12.99985544, -24.89260847, -19.66

In [15]:
densities=gm.score_samples(x)
density_threshold=np.percentile(densities,4)
anomalies=x[densities<density_threshold]

In [16]:
gm.bic(x)

np.float64(36058.55505868701)

In [17]:
gm.aic(x)

np.float64(35975.12321894431)

In [18]:
from sklearn.mixture import BayesianGaussianMixture
bgm=BayesianGaussianMixture(n_components=10,n_init=10)
bgm.fit(x)
np.round(bgm.weights_,2)

array([0.11, 0.11, 0.16, 0.12, 0.12, 0.16, 0.13, 0.1 , 0.  , 0.  ])