<a href="https://colab.research.google.com/github/jiminmini/mini/blob/main/ESAA_YB_WEEK1_assignment%20%EC%88%98%EC%A0%951.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
array1=np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2= np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3=np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

print('array1：{0}차원, array2：{1}차원, array3：{2}차원'.format(array1.ndim,
                                                                 array2.ndim, array3.ndim))

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1：1차원, array2：2차원, array3：2차원


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [24]:
print("Memory size of the array:", array.nbytes, "bytes")

Memory size of the array: 200 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
vector = np.arange(10, 50)
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [11]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [12]:
random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[0.17156718 0.48454101 0.26375935]
  [0.18262109 0.46340643 0.55296987]
  [0.84180823 0.8547489  0.42965163]]

 [[0.26692965 0.90469043 0.74173749]
  [0.70653354 0.8899218  0.72406626]
  [0.08654052 0.53146532 0.45171833]]

 [[0.72458867 0.50565568 0.54515209]
  [0.70130965 0.47831511 0.21169107]
  [0.04355899 0.19069118 0.85656947]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [13]:
random_array = np.random.rand(10, 10)
min_value = np.min(random_array)
max_value = np.max(random_array)

print("Random Array:\n", random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)

Random Array:
 [[6.79904452e-01 4.61809907e-01 2.16463434e-01 7.03780683e-01
  5.89239836e-02 7.10933058e-01 7.33769251e-01 4.38479843e-01
  9.60317625e-01 1.56949261e-01]
 [4.72838216e-01 7.41828405e-01 2.30546176e-02 3.60919859e-01
  2.22198337e-01 2.46525318e-01 9.17157379e-01 2.57426989e-02
  8.30527702e-02 2.18082387e-01]
 [5.69928594e-01 5.65235488e-01 9.68995372e-01 9.22428359e-01
  8.45269082e-01 3.41220381e-01 3.06617499e-01 8.07274963e-01
  6.81680516e-01 4.76351121e-01]
 [8.91142408e-01 1.61449091e-02 3.71557155e-01 9.49700927e-02
  3.21079050e-01 2.98599233e-01 8.67217527e-02 6.97096399e-01
  5.30088804e-01 4.55246971e-01]
 [2.36982050e-02 4.94109357e-01 6.57207470e-01 3.38637048e-01
  7.02726113e-01 5.17825165e-01 1.84081115e-01 6.75705210e-01
  7.50520003e-01 9.83851214e-01]
 [2.35962372e-01 1.69213883e-01 6.31564921e-01 8.90080232e-01
  5.97772994e-01 5.82234520e-01 8.06209742e-01 1.47673697e-01
  2.29217574e-01 6.07179892e-01]
 [9.95348014e-01 2.63425428e-01 4.09528409e

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [14]:
random_vector = np.random.rand(30)
mean_value = np.mean(random_vector)
print("Random Vector:\n", random_vector)
print("\nMean Value:", mean_value)

Random Vector:
 [0.48945115 0.07571978 0.18257354 0.76012126 0.86642928 0.37182434
 0.42495319 0.31345238 0.05092178 0.6153295  0.15587767 0.71157955
 0.44668502 0.18971049 0.89291147 0.75315138 0.09030283 0.17674583
 0.60207266 0.68380504 0.65790469 0.20119182 0.57116415 0.82804358
 0.10563064 0.88645193 0.7429694  0.62581893 0.27821045 0.02870177]

Mean Value: 0.4593235170221901


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
array = np.zeros((5, 5))

In [16]:
array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan       
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```
np.nan

False

False

np.nan

True

False

nan, False, False, nan, True, True

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [18]:
matrix = np.zeros((5, 5))
matrix[np.arange(1, 5), np.arange(0, 4)] = [1, 2, 3, 4]
print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [20]:
index = np.unravel_index(100, (6, 7, 8))
print(index)

(1, 5, 4)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [21]:
X = np.random.rand(5, 5)
X_bar = np.mean(X)
S = np.std(X)
Z = (X - X_bar) / S
print("\nNormalized Matrix (Z):\n", Z)


Normalized Matrix (Z):
 [[ 0.5919131   0.53135321  1.31335712 -0.9566618  -0.40113944]
 [ 1.67700988  0.01445914  1.05403423  0.33933709 -1.34432852]
 [-0.73497188  1.54151494 -1.83274905 -0.84543296  1.06424486]
 [-0.7682196   0.77022912 -0.78972633 -0.60183977 -1.42484683]
 [-0.40690778  0.55978234 -0.79537825  1.51069499 -0.0657278 ]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [23]:
color_dtype = np.dtype([('r', np.ubyte), ('g', np.ubyte), ('b', np.ubyte), ('a', np.ubyte)])
#예시
color_array = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color_dtype)
print(color_array)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 3

In [ ]:
# column 2


In [ ]:
# column 3
