<a href="https://colab.research.google.com/github/jiminmini/mini/blob/main/YB0307_Numpy_exercises%2012%EA%B8%B0%2023%EC%9D%B4%EC%A7%80%EB%AF%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [1]:
import numpy as np

A = np.random.random((5,3))
B = np.random.random((3,2))

print(A)
print(B)
print(np.dot(A,B))

[[0.32763327 0.35816028 0.30796268]
 [0.52659197 0.71344514 0.96784444]
 [0.85542154 0.25374196 0.10160596]
 [0.67229784 0.63751857 0.10974149]
 [0.94766371 0.9629754  0.65945758]]
[[0.90925793 0.86542683]
 [0.74525081 0.20271453]
 [0.76698957 0.30679085]]
[[0.80102655 0.45062705]
 [1.75283008 0.89727833]
 [1.04483094 0.82291372]
 [1.17057395 0.74472655]
 [2.08512603 1.21765826]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [6]:
import numpy as np

A=np.arange(10)
A[(A>3)&(A<8)] *=-1
print(A)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9 ( -1+0+1+2+3+4)
10 (0+1+2+3+4)

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

1,2,4,5 -> 합법적
3,6 -> 비합법적(R)


In [32]:
Z**Z

array([[       1,        1,        4],
       [      27,      256,     3125],
       [   46656,   823543, 16777216]])

In [27]:
2 << Z >> 2

array([[  0,   1,   2],
       [  4,   8,  16],
       [ 32,  64, 128]])

In [28]:
Z <- Z

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [29]:
1j*Z

array([[0.+0.j, 0.+1.j, 0.+2.j],
       [0.+3.j, 0.+4.j, 0.+5.j],
       [0.+6.j, 0.+7.j, 0.+8.j]])

In [30]:
Z/1/1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [31]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

array(nan)
error
value error

In [7]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-7-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-7-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-7-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [8]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.unique(Z1[np.isin(Z1,Z2)]))

[6 2 0 8 6 4 4 2 8 7]
[0 0 2 0 3 9 0 0 3 1]
[0 2]


In [9]:
import numpy as np

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

common_value = np.intersect1d(Z1, Z2)

print("Z1:", Z1)
print("Z2:", Z2)
print(common_value)

Z1: [9 2 6 9 4 9 2 0 1 4]
Z2: [3 4 2 4 5 5 8 7 9 6]
[2 4 6 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j


In [10]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-10-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [11]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [12]:
A=np.random.randint(10)
B=np.random.randint(10)
C=np.add(A,B)
D=np.negative(A)
E=np.divide(D,2)
F=np.multiply(A,E)
print(F)

-12.5


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [13]:
A=np.random.uniform(0,10,5)
print(A//1)

[7. 8. 6. 7. 0.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [14]:
A=np.random.randint(0,5,25).reshape((5,5))
print(A)

[[1 0 0 0 0]
 [4 3 3 0 1]
 [1 3 1 2 4]
 [0 1 2 3 1]
 [4 1 1 3 1]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [5]:
A=np.random.randint(1,11,10)
print(A)
print(np.sort(A))

[ 6  4  9  8  6  1 10  7  7  1]
[ 1  1  4  6  6  7  7  8  9 10]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [15]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(np.array_equal(A,B))

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [25]:
cartesian = np.random.rand(10, 2) * 10
x, y = cartesian[:, 0], cartesian[:, 1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

print("Cartesian Coordinates (x, y):\n", cartesian)
print("\nPolar Coordinates (r, θ):")
print("r =", r)
print("θ =", theta)

Cartesian Coordinates (x, y):
 [[9.70437458 6.26994111]
 [5.84271091 3.40099062]
 [6.81066022 8.64827035]
 [3.90413296 3.35419615]
 [5.6660797  1.88342415]
 [1.24253039 4.16287497]
 [1.48056849 5.36271963]
 [3.87047167 2.91083691]
 [2.71573972 0.25412092]
 [2.85591132 0.15211755]]

Polar Coordinates (r, θ):
r = [11.55365948  6.76047395 11.00807307  5.14712404  5.97090828  4.34435378
  5.56334835  4.84288369  2.72760329  2.85995966]
θ = [0.57362466 0.52714718 0.90371343 0.70977634 0.32091338 1.28073561
 1.30142133 0.64481985 0.09330169 0.05321381]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [16]:
Z=np.random.randint(0,10,10)
Z[Z.argmax()]=0
print(Z)

[2 2 7 3 2 0 3 8 6 9]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [17]:
#


Z = np.arange(100)
v = np.random.uniform(0,100)
distance=np.abs(Z-v)

closest_index=np.argmin(distance)
Z[closest_index]

83

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [24]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [18]:
n = 3
p = 2
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),8)
print(Z)

[[0. 0. 8.]
 [0. 0. 0.]
 [0. 0. 8.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [19]:
# column 1
Z = np.random.randint(0,10,(3,3))
print(Z)
Z[np.argsort(Z[:,0])]

[[1 2 8]
 [4 4 0]
 [7 9 3]]


array([[1, 2, 8],
       [4, 4, 0],
       [7, 9, 3]])

In [20]:
# column 2
Z = np.random.randint(0,10,(3,3))
print(Z)
Z[np.argsort(Z[:,1])]

[[2 1 9]
 [5 2 3]
 [5 0 4]]


array([[5, 0, 4],
       [2, 1, 9],
       [5, 2, 3]])

In [21]:
# column 3
Z = np.random.randint(0,10,(3,3))
print(Z)
Z[np.argsort(Z[:,2])]

[[5 2 2]
 [3 8 1]
 [9 5 1]]


array([[3, 8, 1],
       [9, 5, 1],
       [5, 2, 2]])